apiVersion: v1
kind: Service
metadata:
  name: fz-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: fz-app
spec:
  type: LoadBalancer
  selector:
    app: fz-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
